version: '3.1'

services:
  # DB for bankingapp-users-ms-app
  mysqldb-users-c:
    container_name: mysqldb-users-c
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: clientuser
      MYSQL_PASSWORD: clientpassword
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
      - "3309:3306"
    networks:
      - bankingapp-network  # 🔹 Connect to global network
    volumes:
      - ./mysql-init/usersdb.sql:/docker-entrypoint-initdb.d/usersdb.sql # path to script which should create database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin1234" ]
      interval: 30s
      timeout: 10s
      retries: 3

  bankingapp-users-ms-app:
    image: ihomziak/bankingapp-users-ms:latest
    container_name: users-ms
    ports:
      - "8083:8083"
    networks:
      - bankingapp-network  # 🔹 Connect to global network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8010/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mysqldb-users-c