# Port number
server:
  port: ${SPRING_APPLICATION_PORT}

spring:
  profiles:
    active: dev
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: optional:configserver:${SPRING_CONFIG_SERVER_URL}
  devtools:
    restart:
      enabled: true
  data:
    rest:
      base-path: /api
  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}