spring:
  # MySQL
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    url: jdbc:mysql://${DB_HOST:mysqldb-users-c:3306}/${DB_NAME:users_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:admin1234}

# Logging
logging:
  level:
    org:
      springframework: ERROR
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    com:
      numericaideas: DEBUG
      ihomziak.bankingapp.api.users.dao.AlbumsServiceClient: DEBUG
  file:
    name: users.ws.log