spring:
  application:
    name: users-ms
  config:
    import: optional:configserver:http://localhost:8888
  devtools:
    restart:
      enabled: true

  # MySQL
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3309/${DB_NAME:users_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:admin1234}

  # Hibernate
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # H2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

# Port number
server:
  port: ${PORT:8083}

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      numericaideas: DEBUG
      ihomziak:
        bankingapp:
          api:
            users:
              dao:
                AlbumsServiceClient: DEBUG
  file:
    name: users.ws.log

# Auth
authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

# Login PATH url
login:
  url:
    path: /users/login
# Security
token:
  expiration_time: 24600000
  secret: dgjorufhrsnjdu438fkdj38fdmcv7dm3ckvhrsnjjuwelueivhe848fhedldh5ndk

### Http requests logging for
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      albums-ws:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10000ms
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      albums-ws:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5

### Prometheus, Health, Metrics
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      access: unrestricted
      show-details: always
    prometheus:
      access: unrestricted
    metrics:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    circuitbreakers:
      enabled: true