# Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      numericaideas: DEBUG
      ihomziak:
        bankingapp:
          api:
            users:
              dao:
                AlbumsServiceClient: DEBUG
  file:
    name: users.ws.log

