name: Build & Deploy Spring App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot bankingapp-users-ms
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout основного репозиторію
      - name: Checkout bankingapp-users-ms
        uses: actions/checkout@v4

      # 2️⃣ Checkout спільної бібліотеки bankingapp-common
      - name: Checkout bankingapp-common
        uses: actions/checkout@v4
        with:
          repository: IvanHomziak/bankingapp-common
          path: bankingapp-common

      # 3️⃣ Встановлення JDK 17 + кешування Maven
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      # 4️⃣ Встановлення bankingapp-common
      - name: Install bankingapp-common
        run: |
          cd bankingapp-common
          mvn clean install -DskipTests

      # 5️⃣ Запуск юніт-тестів
      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      # 6️⃣ Верифікація проєкту (опціонально)
      - name: Verify project (Optional)
        run: mvn verify

      # 7️⃣ Збірка JAR
      - name: Build bankingapp-users-ms Application
        run: mvn clean package -DskipTests

      # 8️⃣ Визначення тегу образу
      - name: Define Image Tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      # 9️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 🔟 Setup Docker Buildx (обов’язково для мультиархітектури)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔁 Мультиархітектурна збірка та пуш
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/bankingapp-users-ms:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/bankingapp-users-ms:latest
